#ifndef _RACER_DART_VARDEF_H_
#define _RACER_DART_VARDEF_H_
#define _VARDEF_IGNORE(...)
#define _VARDEF1_SELECT(A0, A1, A2, A3, A4, A5, A6, A7, A8, N, ...) N
#define _VARDEF1_GROUP0(Func, None, ...) None
#define _VARDEF1_GROUP1(Func, None, A, ...) Func(A) _VARDEF1_GROUP0(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP2(Func, None, A, ...) Func(A) _VARDEF1_GROUP1(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP3(Func, None, A, ...) Func(A) _VARDEF1_GROUP2(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP4(Func, None, A, ...) Func(A) _VARDEF1_GROUP3(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP5(Func, None, A, ...) Func(A) _VARDEF1_GROUP4(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP6(Func, None, A, ...) Func(A) _VARDEF1_GROUP5(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP7(Func, None, A, ...) Func(A) _VARDEF1_GROUP6(Func, None, ##__VA_ARGS__)
#define _VARDEF1_GROUP8(Func, None, A, ...) Func(A) _VARDEF1_GROUP7(Func, None, ##__VA_ARGS__)
#define VARDEF1(Func, None, ...) _VARDEF1_SELECT(, ##__VA_ARGS__, _VARDEF1_GROUP8, _VARDEF1_GROUP7, _VARDEF1_GROUP6, _VARDEF1_GROUP5, _VARDEF1_GROUP4, _VARDEF1_GROUP3, _VARDEF1_GROUP2, _VARDEF1_GROUP1, _VARDEF1_GROUP0)(Func, None, ##__VA_ARGS__)
#define _VARDEF2_SELECT(A0, B0, A1, B1, A2, B2, A3, B3, A4, B4, A5, B5, A6, B6, A7, B7, A8, B8, N, ...) N
#define _VARDEF2_GROUP0(Func, None, ...) None
#define _VARDEF2_GROUP1(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP0(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP2(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP1(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP3(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP2(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP4(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP3(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP5(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP4(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP6(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP5(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP7(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP6(Func, None, ##__VA_ARGS__)
#define _VARDEF2_GROUP8(Func, None, A, B, ...) Func(A, B) _VARDEF2_GROUP7(Func, None, ##__VA_ARGS__)
#define VARDEF2(Func, None, ...) _VARDEF2_SELECT(, , ##__VA_ARGS__, _VARDEF2_GROUP8, _VARDEF_IGNORE, _VARDEF2_GROUP7, _VARDEF_IGNORE, _VARDEF2_GROUP6, _VARDEF_IGNORE, _VARDEF2_GROUP5, _VARDEF_IGNORE, _VARDEF2_GROUP4, _VARDEF_IGNORE, _VARDEF2_GROUP3, _VARDEF_IGNORE, _VARDEF2_GROUP2, _VARDEF_IGNORE, _VARDEF2_GROUP1, _VARDEF_IGNORE, _VARDEF2_GROUP0, _VARDEF_IGNORE)(Func, None, ##__VA_ARGS__)
#define _VARDEF3_SELECT(A0, B0, C0, A1, B1, C1, A2, B2, C2, A3, B3, C3, A4, B4, C4, A5, B5, C5, A6, B6, C6, A7, B7, C7, A8, B8, C8, N, ...) N
#define _VARDEF3_GROUP0(Func, None, ...) None
#define _VARDEF3_GROUP1(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP0(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP2(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP1(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP3(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP2(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP4(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP3(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP5(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP4(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP6(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP5(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP7(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP6(Func, None, ##__VA_ARGS__)
#define _VARDEF3_GROUP8(Func, None, A, B, C, ...) Func(A, B, C) _VARDEF3_GROUP7(Func, None, ##__VA_ARGS__)
#define VARDEF3(Func, None, ...) _VARDEF3_SELECT(, , , ##__VA_ARGS__, _VARDEF3_GROUP8, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP7, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP6, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP5, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP4, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP3, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP2, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP1, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF3_GROUP0, _VARDEF_IGNORE, _VARDEF_IGNORE)(Func, None, ##__VA_ARGS__)
#define _VARDEF4_SELECT(A0, B0, C0, D0, A1, B1, C1, D1, A2, B2, C2, D2, A3, B3, C3, D3, A4, B4, C4, D4, A5, B5, C5, D5, A6, B6, C6, D6, A7, B7, C7, D7, A8, B8, C8, D8, N, ...) N
#define _VARDEF4_GROUP0(Func, None, ...) None
#define _VARDEF4_GROUP1(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP0(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP2(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP1(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP3(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP2(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP4(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP3(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP5(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP4(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP6(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP5(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP7(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP6(Func, None, ##__VA_ARGS__)
#define _VARDEF4_GROUP8(Func, None, A, B, C, D, ...) Func(A, B, C, D) _VARDEF4_GROUP7(Func, None, ##__VA_ARGS__)
#define VARDEF4(Func, None, ...) _VARDEF4_SELECT(, , , , ##__VA_ARGS__, _VARDEF4_GROUP8, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP7, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP6, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP5, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP4, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP3, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP2, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP1, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF4_GROUP0, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE)(Func, None, ##__VA_ARGS__)
#define _VARDEF5_SELECT(A0, B0, C0, D0, E0, A1, B1, C1, D1, E1, A2, B2, C2, D2, E2, A3, B3, C3, D3, E3, A4, B4, C4, D4, E4, A5, B5, C5, D5, E5, A6, B6, C6, D6, E6, A7, B7, C7, D7, E7, A8, B8, C8, D8, E8, N, ...) N
#define _VARDEF5_GROUP0(Func, None, ...) None
#define _VARDEF5_GROUP1(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP0(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP2(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP1(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP3(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP2(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP4(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP3(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP5(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP4(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP6(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP5(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP7(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP6(Func, None, ##__VA_ARGS__)
#define _VARDEF5_GROUP8(Func, None, A, B, C, D, E, ...) Func(A, B, C, D, E) _VARDEF5_GROUP7(Func, None, ##__VA_ARGS__)
#define VARDEF5(Func, None, ...) _VARDEF5_SELECT(, , , , , ##__VA_ARGS__, _VARDEF5_GROUP8, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP7, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP6, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP5, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP4, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP3, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP2, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP1, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF5_GROUP0, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE)(Func, None, ##__VA_ARGS__)
#define _VARDEF6_SELECT(A0, B0, C0, D0, E0, F0, A1, B1, C1, D1, E1, F1, A2, B2, C2, D2, E2, F2, A3, B3, C3, D3, E3, F3, A4, B4, C4, D4, E4, F4, A5, B5, C5, D5, E5, F5, A6, B6, C6, D6, E6, F6, A7, B7, C7, D7, E7, F7, A8, B8, C8, D8, E8, F8, N, ...) N
#define _VARDEF6_GROUP0(Func, None, ...) None
#define _VARDEF6_GROUP1(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP0(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP2(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP1(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP3(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP2(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP4(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP3(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP5(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP4(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP6(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP5(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP7(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP6(Func, None, ##__VA_ARGS__)
#define _VARDEF6_GROUP8(Func, None, A, B, C, D, E, F, ...) Func(A, B, C, D, E, F) _VARDEF6_GROUP7(Func, None, ##__VA_ARGS__)
#define VARDEF6(Func, None, ...) _VARDEF6_SELECT(, , , , , , ##__VA_ARGS__, _VARDEF6_GROUP8, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP7, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP6, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP5, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP4, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP3, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP2, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP1, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF6_GROUP0, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE, _VARDEF_IGNORE)(Func, None, ##__VA_ARGS__)
#endif /* _RACER_DART_VARDEF_H_ */